# Use the official Ubuntu base image
FROM ubuntu:latest

# Set the working directory
WORKDIR /app

# Install Node.js and npm
RUN apt-get update 
RUN apt-get install -y nodejs npm
RUN touch euquefiz.txt

# Copy the application files
# COPY minha/pasta/no/host minha/pasta/no/container

# Install application dependencies
# RUN npm install

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]